import assert from "node:assert/strict";
import test from "node:test";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { mkdir, mkdtemp, readFile, realpath, lstat, rm } from "node:fs/promises";
import path from "node:path";
import { createInterface } from "node:readline";
import { createLibraryRecords } from "../../../src/app/library/record-defaults.mts";
import { SourceFronts, platformFront } from "../../../src/core/records/front.mts";
import presets from "../../../src/core/records/front-presets.json" with { type: "json" };
import type { JsonObject } from "../../../src/core/contracts/types.mts";

// Frozen platform identity baseline, not values regenerated by the test.
const expected = {
  chatgpt: "01a0aac8-552c-7af9-a87e-2c52ea363c5e",
  deepseek: "01a0aac8-552d-74da-a60d-bc7b1dd218a4",
  gemini: "01a0aac8-552d-722b-b043-3db3293584d9",
  grok: "01a0aac8-552d-7a9e-8a49-63a007d46f0e",
  doubao: "01a0aac8-552d-732d-b8e2-b058c81149eb",
  kimi: "01a0aac8-552d-7fae-a90c-0b9508fb0a1c",
  qwen: "01a0aac8-552d-778d-b3f0-f359bf6bde36",
  chatglm: "01a0aac8-552d-70da-ba97-8e9f031df267",
  zai: "01a0aac8-552d-7e72-a628-b4b8e6db17cb",
  yuanbao: "01a0aac8-552d-7d6f-905c-36727bcc5e2a",
  mistral: "01a0aac8-552d-7c6f-8564-d6fdf74b18ed",
  claude: "01a0aac8-552d-71af-ab22-054d36bcf8f6"
};
const obj = (v: unknown) => v as JsonObject;

test("twelve platform UUIDs stay frozen and do not merge ChatGLM with Z.ai", () => {
  const actual = Object.fromEntries(presets.presets.filter(p => p.usage === "platform_fallback" && "platform" in p && "front_id" in p).map(p => [p.platform, p.front_id]));
  assert.deepEqual(actual, expected);
  assert.equal(new Set(Object.values(actual)).size, 12);
  for (const id of Object.values(actual)) assert.match(String(id), /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u);
});

test("fresh libraries reuse only platform identities; user and personal assistant remain distinct", () => {
  const create = (timestamp: string) => createLibraryRecords({ timestamp, anchor: { date: timestamp.slice(0, 10), offset: "Z" } });
  const first = create("2026-09-16T12:00:00Z"), second = create("2026-09-17T12:00:00Z");
  const a = first.find(r => r.kind === "identitySettings")!.value, b = second.find(r => r.kind === "identitySettings")!.value;
  assert.deepEqual(a["platforms"], expected); assert.deepEqual(b["platforms"], expected);
  assert.notEqual(a["subject"], b["subject"]); assert.notEqual(a["assistant"], b["assistant"]);
  assert.equal(first.filter(r => r.kind === "identity").length, 14);
  for (const [platform, id] of Object.entries(expected)) {
    const record = first.find(r => r.path === `Identities/${id}.json`)!;
    assert.equal(record.value["front_id"], id); assert.equal(obj(record.value["kind"])["subject"], "ai");
    assert.deepEqual(record.value["names"], platformFront(platform)["names"]);
  }
});

test("fixed platform UUIDs never replace source actors or leak into Conversation Front templates", () => {
  for (const platform of Object.keys(expected)) assert(!Object.hasOwn(platformFront(platform), "front_id"));
  const fronts = new SourceFronts("chatgpt");
  const a = fronts.get({ role: "assistant", name: "model-one", sourceId: "actor-one" });
  const b = fronts.get({ role: "assistant", name: "model-two", sourceId: "actor-two" });
  const tool = fronts.get({ role: "tool", name: "python", sourceId: "tool-one" });
  assert.equal(a, "actor-one"); assert.equal(b, "actor-two"); assert.equal(tool, "tool-one");
  assert.notEqual(a, b); assert.equal(fronts.values.length, 3);
  for (const front of fronts.values) assert(!Object.hasOwn(front, "front_id"));
});

test("external Agent instances get independent source-local Fronts without inheriting the platform name", () => {
  const fronts = new SourceFronts("codex");
  const first = fronts.get({ role: "assistant", sourceId: "agent-thread:one" });
  const second = fronts.get({ role: "assistant", sourceId: "agent-thread:two" });
  assert.notEqual(first, second);
  assert.deepEqual(fronts.values.filter(front => front["source_id"] === first)[0]?.["names"], []);
  assert.deepEqual(fronts.values.filter(front => front["source_id"] === second)[0]?.["names"], []);
});

test("packaged Engine creates the same twelve identities through its real startup protocol", { skip: process.env["CLOUDIG_PLATFORM_PACKAGE"] !== "1", timeout: 30000 }, async () => {
  const base = path.resolve("tests/private/schema-rebuild"); await mkdir(base, { recursive: true });
  const root = await mkdtemp(path.join(base, "platform-front-package-")), app = path.resolve("artifacts/v1-desktop/app/app");
  const child = spawn(path.join(app, "runtime/node/node.exe"), [path.join(app, "engine/engine.mjs"), "--library-root", root, "--cache-root", path.join(root, "cache")], { windowsHide: true, stdio: ["pipe", "pipe", "pipe"] });
  const exited = once(child, "exit"), lines = createInterface({ input: child.stdout }), iterator = lines[Symbol.asyncIterator]();
  let errorText = "", sequence = 0, passed = false;
  child.stderr.setEncoding("utf8"); child.stderr.on("data", value => { errorText += value; });
  const send = async (command: string) => {
    const request = `q_platform_${++sequence}`;
    child.stdin.write(JSON.stringify({ protocol: "cloudig/engine-ipc/1.0.0", kind: "request", request, command, payload: {} }) + "\n");
    for (;;) {
      const line = await iterator.next(); assert(!line.done, `Engine ended before ${command}: ${errorText}`);
      const response = JSON.parse(line.value);
      if (response.kind !== "response" || response.request !== request) continue;
      assert.equal(response.ok, true, JSON.stringify(response)); return response.result;
    }
  };
  try {
    assert.equal((await send("library.startup.recover")).status, "missing");
    assert.equal((await send("library.create")).status, "created");
    const bindings = JSON.parse(await readFile(path.join(root, "Identities/identity-settings.json"), "utf8"));
    assert.deepEqual(bindings.platforms, expected);
    for (const id of Object.values(expected)) assert.equal(JSON.parse(await readFile(path.join(root, `Identities/${id}.json`), "utf8")).front_id, id);
    assert.equal((await send("library.startup.recover")).status, "valid");
    assert.equal((await send("engine.shutdown")).stopped, true); child.stdin.end();
    assert.deepEqual(await exited, [0, null]); assert.equal(errorText, ""); passed = true;
  } finally {
    child.stdin.end(); if (child.exitCode === null && child.signalCode === null) { child.kill(); await exited; }
    lines.close();
    if (passed) {
      assert.equal(path.dirname(await realpath(root)), await realpath(base)); assert(!(await lstat(root)).isSymbolicLink());
      await rm(root, { recursive: true });
    } else console.error(`Retained failed package fixture: ${root}`);
  }
});
