<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cloudig.Bookmarks</RootNamespace>
    <AssemblyName>Cloudig.Bookmarks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cloudig.Bookmarks.Tests" />
  </ItemGroup>
</Project>
